
export const SPECIES = [
    { id: "dog", name: "pet.species.dog", hasBreed: true, icon: "🐶", prefersKg: true },
    { id: "cat", name: "pet.species.cat", hasBreed: true, icon: "🐱", prefersKg: true },
    { id: "smallMammal", name: "pet.species.smallMammal", hasBreed: false, icon: "🐹", prefersKg: false },
    { id: "bird", name: "pet.species.bird", hasBreed: false, icon: "🐦", prefersKg: false },
    { id: "fish", name: "pet.species.fish", hasBreed: false, icon: "🐠", prefersKg: false },
    { id: "reptile", name: "pet.species.reptile", hasBreed: false, icon: "🦎", prefersKg: false },
    { id: "amphibian", name: "pet.species.amphibian", hasBreed: false, icon: "🐸", prefersKg: false },
] as const;

export const dogBreeds = [
    { label: "Akita", id: "akita" },
    { label: "American Staffordshire Terrier", id: "amstaff" },
    { label: "Australian Shepherd", id: "australian shepherd" },
    { label: "Basset Hound", id: "basset" },
    { label: "Beagle", id: "beagle" },
    { label: "Bernese Mountain Dog", id: "bernese" },
    { label: "Bichon Frise", id: "bichon" },
    { label: "Border Collie", id: "border collie" },
    { label: "Boston Terrier", id: "boston terrier" },
    { label: "Boxer", id: "boxer" },
    { label: "Brittany", id: "brittany" },
    { label: "Bulldog", id: "bulldog" },
    { label: "Canary Mastiff", id: "canary mastiff" },
    { label: "Cane Corso", id: "cane corso" },
    { label: "Cavalier King Charles Spaniel", id: "king charles" },
    { label: "Chihuahua", id: "chihuahua" },
    { label: "Cocker Spaniel", id: "cocker" },
    { label: "Collie", id: "collie" },
    { label: "Dachshund", id: "dachshund" },
    { label: "Doberman Pinscher", id: "doberman" },
    { label: "English Setter", id: "english setter" },
    { label: "English Springer Spaniel", id: "english springer" },
    { label: "French Bulldog", id: "french bulldog" },
    { label: "German Shepherd", id: "german shepherd" },
    { label: "German Shorthaired Pointer", id: "german shorthaired" },
    { label: "Golden Retriever", id: "golden retriever" },
    { label: "Great Dane", id: "great dane" },
    { label: "Havanese", id: "havanese" },
    { label: "Irish Setter", id: "irish setter" },
    { label: "Jack Russell Terrier", id: "jack russell" },
    { label: "Labrador Retriever", id: "labrador" },
    { label: "Maltese", id: "maltese" },
    { label: "Mastiff", id: "mastiff" },
    { label: "Miniature Schnauzer", id: "schnauzer" },
    { label: "Mixed Breed", id: "mixed" },
    { label: "Newfoundland", id: "newfoundland" },
    { label: "Pembroke Welsh Corgi", id: "corgi" },
    { label: "Pit Bull Terrier", id: "pitbull" },
    { label: "Pomeranian", id: "pomeranian" },
    { label: "Poodle", id: "poodle" },
    { label: "Pug", id: "pug" },
    { label: "Rottweiler", id: "rottweiler" },
    { label: "Samoyed", id: "samoyed" },
    { label: "Shetland Sheepdog", id: "shetland" },
    { label: "Shiba Inu", id: "shiba inu" },
    { label: "Shih Tzu", id: "shih tzu" },
    { label: "Siberian Husky", id: "husky" },
    { label: "Staffordshire Bull Terrier", id: "staffie" },
    { label: "Unknown", id: "unknown" },
    { label: "Vizsla", id: "vizsla" },
    { label: "Weimaraner", id: "weimaraner" },
    { label: "Yorkshire Terrier", id: "yorkshire" },
];

export const catBreeds = [
    { label: "Abyssinian", id: "abyssinian" },
    { label: "Bengal", id: "bengal" },
    { label: "Birman", id: "birman" },
    { label: "British Shorthair", id: "british shorthair" },
    { label: "Devon Rex", id: "devon rex" },
    { label: "Domestic Longhair", id: "domestic longhair" },
    { label: "Domestic Shorthair", id: "domestic shorthair" },
    { label: "Maine Coon", id: "maine coon" },
    { label: "Mixed Breed", id: "mixed" },
    { label: "Norwegian Forest Cat", id: "norwegian forest cat" },
    { label: "Oriental Shorthair", id: "oriental shorthair" },
    { label: "Persian", id: "persian" },
    { label: "Ragdoll", id: "ragdoll" },
    { label: "Russian Blue", id: "russian blue" },
    { label: "Scottish Fold", id: "scottish fold" },
    { label: "Siamese", id: "siamese" },
    { label: "Sphynx", id: "sphynx" },
    { label: "Unknown", id: "unknown" },
];

export const petFields = {
    name: {
        id: "pet-name",
        label: "pet.form.name",
    },
    species: {
        id: "pet-species",
        name: "pet-species",
        label: "pet.form.species",
        type: "radio",
        options: SPECIES,
    },
    breed: {
        id: "pet-breed",
        label: "pet.form.breed",
        dogOptions: dogBreeds,
        catOptions: catBreeds,
        placeholder: "pet.form.placeholderBreed",
    },
    birthDate: {
        id: "pet-birth",
        label: "pet.form.birthDate",
        type: "date",
    },
    sex: {
        id: "pet-sex",
        label: "pet.form.sex",
        options: [{ id: "male", label: "pet.sex.male" }, { id: "female", label: "pet.sex.female" }],
    },
    sterilized: {
        id: "pet-sterilized",
        label: "pet.form.sterilized",
    },
    microchipped: {
        id: "pet-microchipped",
        label: "pet.form.microchipped",
    }
};