
export const SPECIES = [
    { name: "dog", hasBreed: true, icon: "🐶", prefersKg: true },
    { name: "cat", hasBreed: true, icon: "🐱", prefersKg: true },
    { name: "small mammal", hasBreed: false, icon: "🐹", prefersKg: false },
    { name: "bird", hasBreed: false, icon: "🐦", prefersKg: false },
    { name: "fish", hasBreed: false, icon: "🐠", prefersKg: false },
    { name: "reptile", hasBreed: false, icon: "🦎", prefersKg: false },
    { name: "amphibian", hasBreed: false, icon: "🐸", prefersKg: false },
] as const;

export const SEX = ["male", "female"] as const;

export const dogBreeds = [
    { name: "Mixed Breed", value: "mixed" },
    { name: "Unknown", value: "unknown" },
    { name: "Labrador Retriever", value: "labrador" },
    { name: "German Shepherd", value: "german shepherd" },
    { name: "Golden Retriever", value: "golden retriever" },
    { name: "French Bulldog", value: "french bulldog" },
    { name: "Bulldog", value: "bulldog" },
    { name: "Poodle", value: "poodle" },
    { name: "Beagle", value: "beagle" },
    { name: "Rottweiler", value: "rottweiler" },
    { name: "German Shorthaired Pointer", value: "german shorthaired" },
    { name: "Yorkshire Terrier", value: "yorkshire" },
    { name: "Boxer", value: "boxer" },
    { name: "Dachshund", value: "dachshund" },
    { name: "Siberian Husky", value: "husky" },
    { name: "Cavalier King Charles Spaniel", value: "king charles" },
    { name: "Doberman Pinscher", value: "doberman" },
    { name: "Australian Shepherd", value: "australian shepherd" },
    { name: "Miniature Schnauzer", value: "schnauzer" },
    { name: "Shih Tzu", value: "shih tzu" },
    { name: "Boston Terrier", value: "boston terrier" },
    { name: "Pomeranian", value: "pomeranian" },
    { name: "Havanese", value: "havanese" },
    { name: "Shetland Sheepdog", value: "shetland" },
    { name: "Bernese Mountain Dog", value: "bernese" },
    { name: "Great Dane", value: "great dane" },
    { name: "Pembroke Welsh Corgi", value: "corgi" },
    { name: "Chihuahua", value: "chihuahua" },
    { name: "Border Collie", value: "border collie" },
    { name: "Cocker Spaniel", value: "cocker" },
    { name: "Pug", value: "pug" },
    { name: "Mastiff", value: "mastiff" },
    { name: "Canary Mastiff", value: "canary mastiff" },
    { name: "Maltese", value: "maltese" },
    { name: "Shiba Inu", value: "shiba inu" },
    { name: "English Springer Spaniel", value: "english springer" },
    { name: "English Setter", value: "english setter" },
    { name: "Irish Setter", value: "irish setter" },
    { name: "Brittany", value: "brittany" },
    { name: "Cane Corso", value: "cane corso" },
    { name: "Weimaraner", value: "weimaraner" },
    { name: "Vizsla", value: "vizsla" },
    { name: "Akita", value: "akita" },
    { name: "Bichon Frise", value: "bichon" },
    { name: "Collie", value: "collie" },
    { name: "Basset Hound", value: "basset" },
    { name: "Newfoundland", value: "newfoundland" },
    { name: "Jack Russell Terrier", value: "jack russell" },
    { name: "Staffordshire Bull Terrier", value: "staffie" },
    { name: "American Staffordshire Terrier", value: "amstaff" },
    { name: "Pit Bull Terrier", value: "pitbull" },
    { name: "Samoyed", value: "samoyed" },
] as const;

export const catBreeds = [
    { name: "Mixed Breed", value: "mixed" },
    { name: "Unknown", value: "unknown" },
    { name: "Domestic Shorthair", value: "domestic shorthair" },
    { name: "Domestic Longhair", value: "domestic longhair" },
    { name: "Siamese", value: "siamese" },
    { name: "Maine Coon", value: "maine coon" },
    { name: "Persian", value: "persian" },
    { name: "Ragdoll", value: "ragdoll" },
    { name: "British Shorthair", value: "british shorthair" },
    { name: "Bengal", value: "bengal" },
    { name: "Abyssinian", value: "abyssinian" },
    { name: "Birman", value: "birman" },
    { name: "Oriental Shorthair", value: "oriental shorthair" },
    { name: "Sphynx", value: "sphynx" },
    { name: "Devon Rex", value: "devon rex" },
    { name: "Russian Blue", value: "russian blue" },
    { name: "Scottish Fold", value: "scottish fold" },
    { name: "Norwegian Forest Cat", value: "norwegian forest cat" },
] as const;

export const petFields = {
    name: {
        id: "pet-name",
        label: "Name",
        type: "text",
    },
    species: {
        id: "pet-species",
        name: "pet-species",
        label: "Species",
        type: "radio",
        options: SPECIES,
    },
    breed: {
        id: "breed",
        label: "Breed",
        dogOptions: dogBreeds,
        catOptions: catBreeds,
        placeholder: "Select breed...",
    },
    birthDate: {
        id: "pet-birth",
        label: "Birth date",
        type: "date",
    },
    sex: {
        id: "pet-sex",
        label: "Sex",
        options: SEX,
    },
    sterilized: {
        id: "pet-sterilized",
        label: "Spayed / neutered",
    },
    microchipped: {
        id: "pet-microchipped",
        label: "Microchipped",
    }
};